# Generated by Django 4.1.2 on 2023-01-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0002_alter_infrastructure_no_of_tie_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='no_of_tie_up',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
