# Generated by Django 4.0.3 on 2022-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desktop',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
