# Generated by Django 4.0.3 on 2022-11-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0003_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='amt_of_sponsorship',
        ),
    ]
