# Generated by Django 4.0.3 on 2022-11-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0004_remove_events_amt_of_sponsorship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='sponsored_by',
            new_name='sponsores_details',
        ),
    ]
