# Generated by Django 4.1.2 on 2022-11-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0005_events_departments_events_societies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upload_attendance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='upload_report',
            field=models.CharField(max_length=255),
        ),
    ]
