# Generated by Django 4.0.3 on 2022-11-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0005_rename_sponsored_by_events_sponsores_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='sponsores_details',
            new_name='sponsors_details',
        ),
    ]
