# Generated by Django 4.0.3 on 2022-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0006_rename_sponsores_details_events_sponsors_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='total_sponsored_amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
