# Generated by Django 4.0.3 on 2022-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0006_events_upload_report_alter_events_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upload_report',
            field=models.FileField(upload_to='report/event_reports/'),
        ),
    ]
