# Generated by Django 4.1.2 on 2022-11-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0004_delete_desktop_delete_laptop_delete_mobile_and_more'),
        ('manage_data', '0007_events_total_sponsored_amt'),
    ]

    operations = [
    ]
