# Generated by Django 4.1.2 on 2022-12-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0007_alter_events_type_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
