# Generated by Django 4.0.3 on 2022-11-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0007_alter_events_upload_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Departments',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('Applied Science', 'Applied Science'), ('All', 'All'), ('None', 'None')], default='None', max_length=255),
        ),
    ]
