# Generated by Django 4.1.2 on 2022-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0008_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'REGULAR'), ('upgraded', 'UPGRADED'), ('le', 'LE')], default='Regular', max_length=10)),
                ('enrollmentno', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('management', models.BooleanField(default=False)),
                ('yearofadmission', models.DateTimeField(default=False)),
                ('appno', models.CharField(default=False, max_length=200)),
                ('Fname', models.CharField(default=False, max_length=200)),
                ('Mname', models.CharField(default=False, max_length=200)),
                ('stream', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], default=False, max_length=200)),
                ('DOB', models.DateField(default=False)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=False, max_length=50)),
                ('category', models.CharField(choices=[('gen', 'GEN'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('aicte', 'AICTE')], default=False, max_length=5)),
                ('subcategory', models.CharField(choices=[('defence', 'DEFENCE'), ('jain', 'JAIN'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('pwd', 'PWD'), ('jk', 'JK')], default=False, max_length=10)),
                ('region', models.CharField(choices=[('delhi', 'DELHI'), ('outside delhi', 'OUTSIDE DELHI')], default=False, max_length=50)),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('allottedquota', models.CharField(choices=[('opno', 'OPNO'), ('scno', 'SCNO'), ('stno', 'STNO'), ('nodf', 'NODF'), ('noph', 'NOPH')], default=False, max_length=10)),
                ('allottedcategory', models.CharField(choices=[('hs', 'HS'), ('os', 'OS'), ('ai', 'AI')], default=False, max_length=10)),
                ('studentmobile', models.IntegerField(blank=True, default=None, null=True)),
                ('emailid', models.EmailField(default=False, max_length=20)),
                ('fathermobile', models.IntegerField(blank=True, default=None, null=True)),
                ('address', models.CharField(default=False, max_length=200)),
                ('aggregate', models.FloatField(blank=True, default=None, null=True)),
                ('pcm', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusEntrepreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('startup_name', models.CharField(default=False, max_length=100)),
                ('address', models.CharField(default=False, max_length=255)),
                ('startup_country', models.CharField(default=False, max_length=100)),
                ('sector', models.CharField(default=False, max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusHighEduDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('college_name', models.CharField(default=False, max_length=100)),
                ('course_name', models.CharField(default=False, max_length=100)),
                ('country_name', models.CharField(default=False, max_length=100)),
                ('college_address', models.CharField(default=False, max_length=255)),
                ('id_proof', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('company_name', models.CharField(default=False, max_length=100)),
                ('date_of_joining', models.DateField()),
                ('address', models.CharField(default=False, max_length=255)),
                ('joining_proof', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('exam_name', models.CharField(default=False, max_length=100)),
                ('exam_roll_no', models.BigIntegerField(default=None)),
                ('exam_date', models.DateField()),
                ('qualified', models.CharField(default=False, max_length=20)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('date_of_result', models.DateField(blank=True, null=True)),
                ('result_proof', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('company_name', models.CharField(default=False, max_length=100)),
                ('package_in_lpa', models.IntegerField(default=None)),
                ('on_off_campus', models.CharField(default=None, max_length=15)),
                ('job_proof', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], default=False, max_length=200)),
                ('section', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('All', 'All')], default=False, max_length=15)),
                ('passout', models.DateField(default=False)),
                ('is_placed', models.BooleanField(default=False)),
                ('appeared_for_exams', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('Job', 'Job'), ('Higher Education', 'Higher Education'), ('Entreprenurship', 'Entreprenurship'), ('Others', 'Others')], default=None, max_length=50)),
            ],
        ),
    ]
