# Generated by Django 4.1.2 on 2022-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0005_events_departments_events_societies_and_more'),
        ('manage_data', '0008_alter_events_departments'),
    ]

    operations = [
    ]
