# Generated by Django 4.1.2 on 2022-11-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0006_alter_events_upload_attendance_and_more'),
        ('manage_data', '0008_alter_events_departments'),
    ]

    operations = [
    ]
