# Generated by Django 4.1.2 on 2022-12-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0008_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'REGULAR'), ('upgraded', 'UPGRADED'), ('le', 'LE')], default='Regular', max_length=10)),
                ('enrollmentno', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('management', models.BooleanField(default=False)),
                ('yearofadmission', models.DateTimeField(default=False)),
                ('appno', models.CharField(default=False, max_length=200)),
                ('Fname', models.CharField(default=False, max_length=200)),
                ('Mname', models.CharField(default=False, max_length=200)),
                ('stream', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], default=False, max_length=200)),
                ('DOB', models.DateField(default=False)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=False, max_length=50)),
                ('category', models.CharField(choices=[('gen', 'GEN'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('aicte', 'AICTE')], default=False, max_length=5)),
                ('subcategory', models.CharField(choices=[('defence', 'DEFENCE'), ('jain', 'JAIN'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('pwd', 'PWD'), ('jk', 'JK')], default=False, max_length=10)),
                ('region', models.CharField(choices=[('delhi', 'DELHI'), ('outside delhi', 'OUTSIDE DELHI')], default=False, max_length=50)),
                ('rank', models.IntegerField(blank=True, default=None, null=True)),
                ('allottedquota', models.CharField(choices=[('opno', 'OPNO'), ('scno', 'SCNO'), ('stno', 'STNO'), ('nodf', 'NODF'), ('noph', 'NOPH')], default=False, max_length=10)),
                ('allottedcategory', models.CharField(choices=[('hs', 'HS'), ('os', 'OS'), ('ai', 'AI')], default=False, max_length=10)),
                ('studentmobile', models.IntegerField(blank=True, default=None, null=True)),
                ('emailid', models.EmailField(default=False, max_length=20)),
                ('fathermobile', models.IntegerField(blank=True, default=None, null=True)),
                ('address', models.CharField(default=False, max_length=200)),
                ('aggregate', models.FloatField(blank=True, default=None, null=True)),
                ('pcm', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
