# Generated by Django 4.1.2 on 2022-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0009_student_studentcurrentstatusentrepredetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Cultural', 'Cultural'), ('Technical', 'Technical'), ('Sports', 'Sports')], max_length=30)),
                ('event_date', models.DateField()),
                ('organized_by', models.CharField(max_length=255)),
                ('host_institute', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('Runner_up', 'Runner_up')], max_length=20)),
                ('team_size', models.CharField(choices=[('Team', 'Team'), ('Individual', 'Individual')], max_length=20)),
                ('level', models.CharField(choices=[('College', 'College'), ('InterCollege', 'InterCollege'), ('University', 'University'), ('State', 'State'), ('National', 'National'), ('International', 'International')], default='College', max_length=30)),
                ('date_of_award', models.DateField()),
                ('upload_proof', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_award',
        ),
        migrations.RemoveField(
            model_name='students',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='students',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='students',
            name='host_institute',
        ),
        migrations.RemoveField(
            model_name='students',
            name='level',
        ),
        migrations.RemoveField(
            model_name='students',
            name='organized_by',
        ),
        migrations.RemoveField(
            model_name='students',
            name='position',
        ),
        migrations.RemoveField(
            model_name='students',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='students',
            name='upload_proof',
        ),
    ]
