# Generated by Django 4.1.2 on 2022-12-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], default=False, max_length=200)),
                ('section', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('All', 'All')], default=False, max_length=15)),
                ('passout', models.DateField(default=False)),
            ],
        ),
    ]
