# Generated by Django 4.1.2 on 2023-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0009_student_studentcurrentstatusentrepredetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Fname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='Mname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='allottedcategory',
            field=models.CharField(choices=[('hs', 'HS'), ('os', 'OS'), ('ai', 'AI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='allottedquota',
            field=models.CharField(choices=[('opno', 'OPNO'), ('scno', 'SCNO'), ('stno', 'STNO'), ('nodf', 'NODF'), ('noph', 'NOPH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='appno',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('gen', 'GEN'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('ews', 'EWS'), ('aicte', 'AICTE')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='emailid',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathermobile',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='management',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(choices=[('delhi', 'DELHI'), ('outside delhi', 'OUTSIDE DELHI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentmobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='subcategory',
            field=models.CharField(choices=[('defence', 'DEFENCE'), ('jain', 'JAIN'), ('muslim', 'MUSLIM'), ('sikh', 'SIKH'), ('pwd', 'PWD'), ('jk', 'JK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearofadmission',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusentrepredetails',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusentrepredetails',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusentrepredetails',
            name='startup_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusentrepredetails',
            name='startup_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatushighedudetails',
            name='college_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatushighedudetails',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatushighedudetails',
            name='country_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatushighedudetails',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusjobdetails',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentcurrentstatusjobdetails',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentexamdetails',
            name='exam_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentexamdetails',
            name='qualified',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentofferdetails',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('it', 'IT'), ('ece', 'ECE'), ('eee', 'EEE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='passout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='section',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('All', 'All')], max_length=15),
        ),
    ]
