# Generated by Django 4.1.2 on 2022-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0010_studentplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCurrentStatusEntrepreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('startup_name', models.CharField(default=False, max_length=100)),
                ('address', models.CharField(default=False, max_length=255)),
                ('sector', models.CharField(default=False, max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusHighEduDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('college_name', models.CharField(default=False, max_length=100)),
                ('course_name', models.CharField(default=False, max_length=100)),
                ('country_name', models.CharField(default=False, max_length=100)),
                ('id_proof', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusJobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('company_name', models.CharField(default=False, max_length=100)),
                ('date_of_joining', models.DateField()),
                ('address', models.CharField(default=False, max_length=255)),
                ('joining_proof', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCurrentStatusOtherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('other', models.CharField(blank=True, default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('exam_name', models.CharField(default=False, max_length=100)),
                ('exam_roll_no', models.BigIntegerField(default=None)),
                ('exam_date', models.DateField(default=False)),
                ('qualified', models.BooleanField()),
                ('score', models.IntegerField(blank=True, default=None)),
                ('rank', models.IntegerField(blank=True, default=None)),
                ('result_proof', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentOfferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.IntegerField(default=None, null=True)),
                ('company_name', models.CharField(default=False, max_length=100)),
                ('package_in_lpa', models.IntegerField(default=None)),
                ('on_off_campus', models.CharField(default=None, max_length=5)),
                ('job_proof', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='appeared_for_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='current_status',
            field=models.CharField(choices=[('Job', 'Job'), ('Higher Education', 'Higher Education'), ('Entreprenurship', 'Entreprenurship'), ('Others', 'Others')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
