# Generated by Django 4.1.2 on 2022-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0010_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='organised_by',
            new_name='organized_by',
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='students',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
