# Generated by Django 4.1.2 on 2023-01-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0010_alter_student_dob_alter_student_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upload_attendance',
            field=models.FileField(upload_to='event_attendance/'),
        ),
    ]
