# Generated by Django 4.1.2 on 2023-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0011_alter_events_upload_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='upload_report',
            field=models.FileField(upload_to='event/reports/'),
        ),
    ]
