# Generated by Django 4.1.2 on 2022-12-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0011_students_fk_alter_student_dob_alter_student_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fk',
            new_name='event_id',
        ),
    ]
