# Generated by Django 4.1.2 on 2023-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0011_alter_studentplacement_current_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='eroll_no',
            new_name='enroll_no',
        ),
        migrations.AlterField(
            model_name='students',
            name='Class',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='position',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=20),
        ),
    ]
