# Generated by Django 4.1.2 on 2022-12-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0011_studentcurrentstatusentrepredetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamdetails',
            name='qualified',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
