# Generated by Django 4.1.2 on 2022-12-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0011_rename_organised_by_students_organized_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
