# Generated by Django 4.1.2 on 2022-12-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0012_alter_studentexamdetails_qualified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCurrentStatusOtherDetails',
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='current_status',
            field=models.CharField(choices=[('Job', 'Job'), ('Higher Education', 'Higher Education'), ('Entreprenurship', 'Entreprenurship'), ('Others', 'Others')], default=None, max_length=50),
        ),
    ]
