# Generated by Django 4.1.2 on 2022-12-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0013_delete_studentcurrentstatusotherdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentofferdetails',
            name='on_off_campus',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
