# Generated by Django 4.1.2 on 2023-03-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0013_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='upload_proof',
            field=models.FileField(upload_to='students/upload_proof/'),
        ),
    ]
