# Generated by Django 4.1.2 on 2023-01-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0013_rename_enroll_no_students_eroll_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='DefaultStudent',
        ),
    ]
