# Generated by Django 4.1.2 on 2023-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0014_rename_student_defaultstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentplacement',
            name='current_status',
            field=models.CharField(choices=[('Job', 'Job'), ('Higher Education', 'Higher Education'), ('Entreprenurship', 'Entreprenurship'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
