# Generated by Django 4.1.2 on 2022-12-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0014_alter_studentofferdetails_on_off_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamdetails',
            name='rank',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamdetails',
            name='result_proof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamdetails',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
