# Generated by Django 4.1.2 on 2022-12-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0015_alter_studentexamdetails_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcurrentstatusentrepredetails',
            name='startup_country',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='studentcurrentstatushighedudetails',
            name='college_address',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='studentexamdetails',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexamdetails',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
