from django import forms
from .models import *

class EventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ('event_name','type_of_event','Audience','Societies','Departments','Organized_by','Conducted_by','no_of_sponsors','sponsors_details','total_sponsored_amt','start_date','end_date','no_of_participants','upload_attendance','upload_report')

class StudentForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = '__all__'

class InfraForm(forms.ModelForm):
    class Meta:
        model = Infrastructure
        fields = ('for_year_infra_entry','name_of_the_institute','institute_category','name_of_affiliating_university','institution_status','institute_type','year_of_establishment','year_of_1st_passout_batch','address','city','state','pincode','campus_area','total_built_up_area_in_sqmtr','total_built_up_area_in_sqft','total_playground_area','phone','email','website','head_of_the_institute','name_of_the_head_of_institution','available_courses','no_of_voluntary_programs_supported','AICTE_approved','date_of_first_AICTE_accreditation','AICTE_valid_upto','NAAC_accredited','year_of_first_NAAC_accreditation','latest_NAAC_grade','latest_NAAC_score','NAAC_accreditation_valid_upto','date_of_last_submitted_AQAR_report','ABET_accredited','NBA_accredited_courses','NBA_accreditation_valid_upto','proof_UGC_recognition','proof_yr_of_estb_of_college','latest_AICTE_renewed_approval_certificate','NBA_accreditation_certificate','NAAC_accreditation_certificate','latest_AQAR_submitted_to_NAAC','list_of_governing_body_members','list_of_academic_advisory_body','list_of_members_in_anti_ragging_committee','list_of_members_in_internal_complaint_committee','list_of_members_in_grievance_redressal_committee','list_of_members_in_disciplane_committee','list_of_members_in_ST_SC_cell','list_of_members_in_disaster_management_cell','list_of_members_in_NSS','number_of_classrooms','no_of_seminar_halls','no_of_classrooms_with_audio_visual_facility','no_of_labs','no_of_computer_labs','no_of_auditoriums','total_sitting_capacity_in_main_auditorium','no_of_conference_rooms','no_of_recreation_rooms','no_of_faculty_cabins','no_of_PCs_provided_to_student','no_of_PCs_provided_to_faculty','no_of_PCs_provided_to_other_than_faculty','total_PCs_in_campus','no_of_latest_instruments_in_labs','availability_of_water_recyling_unit','availability_of_anti_ragging_cell','availability_of_grievance_redressal_mechanism','availability_of_internal_complaints_commitee','availability_of_NSS_cell','availability_of_IQAC','availability_of_faculty_feedback_mechanism','availability_of_alumini_association','no_of_alumini','availability_of_incubation_centre','no_of_companies_setup_in_last_5_years_by_incubation_centre','hostel_facilities_for_boys','area_of_boys_hostel','capacity_of_boys_hostel','no_of_boys_in_hostel','hostel_facilities_for_girls','area_of_girls_hostel','capacity_of_girls_hostel','no_of_girls_in_hostel','no_of_students_availing_hostel_facilities','residence_facility_for_faculty','total_staff_quarters','how_many_faculties_residing_in_college_campus','no_of_faculties_visited_any_foreign_university_in_previous_AY','institute_tieup_with_foreign_university','tieup_university_details','no_of_tie_up','no_of_clubs_in_college','club_details','canteen','cricket_ground','basketball_court','football_ground','swimming_pool','lawn_tennis_court','badminton_court','bank_branch','wifi_facilities','table_tennis_boards','gymnasium','bank_ATM','no_of_publications_by_college','publication_details')        