from django.db import models
from django.core.validators import RegexValidator

class Infrastructure(models.Model):
    for_year_infra_entry = models.IntegerField()
    name_of_the_institute = models.CharField(max_length=255,blank=False)         
    institute_category = models.CharField(max_length=255,default='Affiliated to a University')
    name_of_affiliating_university = models.CharField(max_length=255,blank=False)
    Institute_Type = (
        ('Private Aided','Private Aided'),
        ('Private Unaided','Private Unaided')
    )
    institution_status=models.CharField(max_length=255,blank=False )
    institute_type = models.CharField(max_length=255, choices=Institute_Type,default=None,blank=False)
    year_of_establishment = models.IntegerField()
    year_of_1st_passout_batch = models.IntegerField()
    address = models.CharField(max_length=255, blank=False)
    city=models.CharField(max_length=50,blank=False)
    state=models.CharField(max_length=50,blank=False)
    pincode=models.IntegerField()
    campus_area = models.DecimalField(max_digits=5,decimal_places=2)
    total_built_up_area_in_sqmtr = models.IntegerField()
    total_built_up_area_in_sqft =models.IntegerField()
    total_playground_area=models.IntegerField()
    phone_regex = RegexValidator(regex='^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s./0-9]*$',message="Phone number must be a 10 digit number")
    phone = models.CharField(validators=[phone_regex],max_length=13,blank=False)
    email = models.EmailField(max_length=254) 
    website = models.URLField(max_length=200)
    head_of_the_institute = models.CharField(default='Director',max_length=255)
    name_of_the_head_of_institution = models.CharField(max_length=255)
    available_courses = models.CharField(max_length=255)
    no_of_voluntary_programs_supported=models.IntegerField(default=1)
    choice=(
        ('Yes','Yes'),
        ('No','No')
    )
    AICTE_approved = models.CharField(choices=choice,default='Yes',max_length=255)
    date_of_first_AICTE_accreditation = models.DateField(blank=False)
    AICTE_valid_upto = models.IntegerField()
    NAAC_accredited = models.CharField(choices=choice,default='Yes',max_length=255)
    year_of_first_NAAC_accreditation = models.IntegerField()
    latest_NAAC_grade = models.CharField(max_length=10)
    latest_NAAC_score = models.IntegerField()
    NAAC_accreditation_valid_upto =models.IntegerField()
    date_of_last_submitted_AQAR_report = models.DateField()
    ABET_accredited = models.CharField(choices=choice,default='No',max_length=255)
    NBA_accredited_courses=models.CharField(choices=choice,default='Yes',max_length=255)
    NBA_accreditation_valid_upto=models.IntegerField()
    proof_UGC_recognition=models.CharField(blank=False,max_length=255)
    proof_yr_of_estb_of_college=models.CharField(blank=False,max_length=255)
    latest_AICTE_renewed_approval_certificate=models.CharField(blank=False,max_length=255)
    NBA_accreditation_certificate=models.CharField(blank=False,max_length=255)
    NAAC_accreditation_certificate=models.CharField(blank=False,max_length=255)
    latest_AQAR_submitted_to_NAAC=models.CharField(blank=False,max_length=255)
    list_of_governing_body_members=models.CharField(blank=False,max_length=255)
    list_of_academic_advisory_body=models.CharField(blank=False,max_length=255)
    list_of_members_in_anti_ragging_committee=models.CharField(blank=False,max_length=255,)
    list_of_members_in_internal_complaint_committee=models.CharField(blank=False,max_length=255)
    list_of_members_in_grievance_redressal_committee=models.CharField(blank=False,max_length=255)
    list_of_members_in_disciplane_committee=models.CharField(blank=False,max_length=255)
    list_of_members_in_ST_SC_cell=models.CharField(blank=False,max_length=255)
    list_of_members_in_disaster_management_cell=models.CharField(blank=False,max_length=255)
    list_of_members_in_NSS=models.CharField(blank=False,max_length=255)
    number_of_classrooms =models.IntegerField()
    no_of_seminar_halls=models.IntegerField()
    no_of_classrooms_with_audio_visual_facility = models.IntegerField()
    no_of_labs= models.IntegerField()
    no_of_computer_labs=models.IntegerField()
    no_of_auditoriums =models.IntegerField()
    total_sitting_capacity_in_main_auditorium=models.IntegerField()
    no_of_conference_rooms=models.IntegerField()
    no_of_recreation_rooms=models.IntegerField()
    no_of_faculty_cabins=models.IntegerField()
    no_of_PCs_provided_to_student=models.IntegerField()
    no_of_PCs_provided_to_faculty=models.IntegerField()
    no_of_PCs_provided_to_other_than_faculty=models.IntegerField()
    total_PCs_in_campus=models.IntegerField()
    no_of_latest_instruments_in_labs=models.IntegerField()
    availability_of_water_recyling_unit=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_anti_ragging_cell=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_grievance_redressal_mechanism=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_internal_complaints_commitee=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_NSS_cell=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_IQAC=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_faculty_feedback_mechanism=models.CharField(max_length=255,choices=choice,default='Yes')
    availability_of_alumini_association=models.CharField(max_length=255,choices=choice,default='Yes')
    no_of_alumini=models.IntegerField()
    availability_of_incubation_centre=models.CharField(max_length=255,choices=choice,default='Yes')
    no_of_companies_setup_in_last_5_years_by_incubation_centre=models.IntegerField()
    hostel_facilities_for_boys=models.CharField(max_length=255,choices=choice,default='Yes')
    area_of_boys_hostel=models.IntegerField()
    capacity_of_boys_hostel=models.IntegerField()
    no_of_boys_in_hostel=models.IntegerField()
    hostel_facilities_for_girls=models.CharField(max_length=255,choices=choice,default='Yes')
    area_of_girls_hostel=models.IntegerField()
    capacity_of_girls_hostel=models.IntegerField()
    no_of_girls_in_hostel=models.IntegerField()
    no_of_students_availing_hostel_facilities=models.IntegerField()
    residence_facility_for_faculty=models.CharField(max_length=255,choices=choice,default='Yes')
    total_staff_quarters=models.IntegerField()
    how_many_faculties_residing_in_college_campus=models.IntegerField()
    no_of_faculties_visited_any_foreign_university_in_previous_AY=models.IntegerField()
    institute_tieup_with_foreign_university=models.CharField(choices=choice,default='No',max_length=10)
    no_of_tie_up=models.IntegerField(null=True,blank=True,default=0)
    tieup_university_details=models.CharField(blank=False,max_length=255,null=True)
    no_of_clubs_in_college=models.IntegerField(blank=False)
    club_details=models.CharField(max_length=255,blank=False)
    canteen=models.CharField(max_length=255,choices=choice,default='Yes')
    cricket_ground=models.CharField(max_length=255,choices=choice,default='Yes')
    basketball_court=models.CharField(max_length=255,choices=choice,default='Yes')
    football_ground=models.CharField(max_length=255,choices=choice,default='Yes')
    swimming_pool=models.CharField(max_length=255,choices=choice,default='No')
    lawn_tennis_court = models.CharField(max_length=255,choices=choice,default='Yes')
    badminton_court=models.CharField(max_length=255,choices=choice,default='Yes')
    bank_branch=models.CharField(max_length=255,choices=choice,default='Yes')
    wifi_facilities=models.CharField(max_length=255,choices=choice,default='Yes')
    table_tennis_boards=models.CharField(max_length=255,choices=choice,default='Yes')
    gymnasium=models.CharField(max_length=255,choices=choice,default='Yes')
    bank_ATM=models.CharField(max_length=255,choices=choice,default='Yes')
    no_of_publications_by_college=models.IntegerField(default=0)
    publication_details=models.CharField(max_length=255,blank=False)

    def __str__(self):
        return self.name_of_the_institute

    